inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'examples/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'lib/claude_agent_sdk.rb'
    - 'lib/claude_agent_sdk/query.rb'
    - 'lib/claude_agent_sdk/message_parser.rb'
    - 'lib/claude_agent_sdk/sdk_mcp_server.rb'
    - 'lib/claude_agent_sdk/subprocess_cli_transport.rb'
    - 'lib/claude_agent_sdk/types.rb'

Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'lib/claude_agent_sdk/query.rb'
    - 'lib/claude_agent_sdk/message_parser.rb'
    - 'lib/claude_agent_sdk/subprocess_cli_transport.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/claude_agent_sdk.rb'
    - 'lib/claude_agent_sdk/types.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
