# frozen_string_literal: true

module ClaudeAgentSDK
  # Attribute declarations and the rules #[], #[]=, .new and the camelCase
  # readers follow (issue #126). Loaded by base.rb right after Type itself,
  # before any subclass declares an attribute.
  class Type
    LENIENT_KEY = :__claude_agent_sdk_lenient_attributes
    private_constant :LENIENT_KEY

    class << self
      # attr_accessor / attr_reader / attr_writer also declare the names as
      # attributes (see .attribute_names). Inherited by subclasses.
      #
      # @api private
      def attr_accessor(*names)
        declare_attributes(*names)
        super
      end

      # @api private
      def attr_reader(*names)
        declare_attributes(*names)
        super
      end

      # @api private
      def attr_writer(*names)
        declare_attributes(*names)
        super
      end

      private

      def own_attribute_names
        @own_attribute_names ||= Set.new
      end
    end

    # Declares hand-written readers or writers (a method not generated by
    # attr_*, such as a backward-compatible reader) as attributes, so #[],
    # #[]= and the camelCase readers reach them.
    #
    # @api private
    def self.declare_attributes(*names)
      names.each { |name| own_attribute_names << name.to_s }
    end

    # Whether +name+ (snake_case String) is a declared attribute of this
    # class or an ancestor.
    #
    # @api private
    def self.attribute?(name)
      own_attribute_names.include?(name) || (superclass <= Type && superclass.attribute?(name))
    end

    # Whether +method_name+ (a normalized reader, writer or predicate:
    # `session_id`, `session_id=`, `fork_session?`) accesses a declared
    # attribute.
    #
    # @api private
    def self.attribute_method?(method_name)
      attribute?(method_name.delete_suffix('=').delete_suffix('?'))
    end

    # Per-class caches of the names, exactly as callers spell them (:sessionId,
    # 'session_id', ...), that reached a declared attribute: name => method.
    # Hits skip name normalization and the checks below. Only positives are
    # cached: the registry only grows, so they never go stale (an answer that
    # depends on user-defined methods is never cached). Bounded by attributes
    # x spellings. Replaced, never mutated, so readers need no lock.
    #
    # @api private
    def self.cached_attribute_reader(name)
      @attribute_readers&.[](name)
    end

    # @api private
    def self.cached_attribute_writer(name)
      @attribute_writers&.[](name)
    end

    # @api private
    def self.cache_attribute_reader(name, method_name)
      @attribute_readers = (@attribute_readers || {}).merge(name => method_name).freeze
    end

    # @api private
    def self.cache_attribute_writer(name, method_name)
      @attribute_writers = (@attribute_writers || {}).merge(name => method_name).freeze
    end

    # Every declared attribute name (snake_case), sorted.
    #
    # @api private
    def self.attribute_names
      inherited = superclass <= Type ? superclass.attribute_names : []
      (inherited | own_attribute_names.to_a).sort
    end

    # Declares a type the user constructs and passes IN (option values, hook
    # matchers and outputs, permission results and updates). Constructing
    # one directly (.new or #[]=) with a key that is not an attribute raises
    # ArgumentError — a typo would otherwise be dropped silently (0.37 warned
    # here; 1.0 raises). A read-only attribute (the +type+,
    # +hook_event_name+ or +behavior+ discriminator a type sets itself, which
    # its own #to_h emits) is accepted and ignored. Types the SDK parses from
    # CLI output stay lenient so a newer CLI's extra fields never break an
    # older SDK; so does every construction through .from_hash or .wrap.
    # Inherited by subclasses.
    #
    # @api private
    def self.strict_attributes
      @strict_attributes = true
    end

    # @api private
    def self.strict_attributes?
      @strict_attributes || (superclass <= Type && superclass.strict_attributes?)
    end

    # Runs the block with the strict-attribute check off on this fiber, for
    # the SDK's own parse paths (CLI payloads and their nested values).
    def self.lenient
      previous = Thread.current[LENIENT_KEY]
      Thread.current[LENIENT_KEY] = true
      yield
    ensure
      Thread.current[LENIENT_KEY] = previous
    end
    private_class_method :lenient

    private

    # Allow camelCase attribute access
    def method_missing(method_name, ...)
      target = self.class.cached_attribute_reader(method_name)
      return public_send(target, ...) if target

      normalized = normalize_name(method_name)
      if normalized != method_name.to_s && respond_to?(normalized)
        if self.class.attribute_method?(normalized)
          self.class.cache_attribute_reader(method_name, normalized.to_sym)
          return public_send(normalized, ...)
        end
        return public_send(normalized, ...) if user_defined_method?(normalized)
      end
      super
    end

    def respond_to_missing?(method_name, include_private = false)
      normalized = normalize_name(method_name)
      (normalized != method_name.to_s && respond_to?(normalized) && attribute_method?(normalized)) || super
    end

    def assign_attributes(attributes)
      unless attributes.respond_to?(:each_pair)
        raise ArgumentError,
              "When assigning attributes, you must pass a hash as an argument, #{attributes.inspect} passed."
      end

      return if attributes.empty?

      attributes.each_pair { |name, value| assign_attribute(name, value) }
    end

    def assign_attribute(name, value)
      writer = self.class.cached_attribute_writer(name)
      return public_send(writer, value) if writer

      normalized = normalize_name(name)
      setter = :"#{normalized}="
      if respond_to?(setter)
        if self.class.attribute?(normalized)
          self.class.cache_attribute_writer(name, setter)
          return public_send(setter, value)
        end
        return public_send(setter, value) if user_defined_method?(setter.to_s)
      end
      return unless self.class.strict_attributes? && !Thread.current[LENIENT_KEY] && !self.class.attribute?(normalized)
      return if respond_to?(normalized) && user_defined_method?(normalized)

      unknown_attribute(name)
    end

    def read_attribute(name)
      reader = self.class.cached_attribute_reader(name)
      return public_send(reader) if reader

      getter = normalize_name(name)
      return unless respond_to?(getter)

      if self.class.attribute_method?(getter)
        self.class.cache_attribute_reader(name, getter.to_sym)
        public_send(getter)
      elsif user_defined_method?(getter)
        public_send(getter)
      end
    end

    # Whether a normalized reader, writer or predicate name belongs to an
    # attribute: a declared one (`session_id`, `session_id=`,
    # `fork_session?`), or a method user code defined on its own subclass, a
    # module it includes, or the object itself. Only methods the SDK, Ruby or
    # another gem defines at Type or above (to_h, freeze, to_json, ...) are
    # not attributes.
    def attribute_method?(method_name)
      self.class.attribute_method?(method_name) || user_defined_method?(method_name)
    end

    # Not memoized: user code can define methods at any time.
    def user_defined_method?(method_name)
      owner = method(method_name).owner
      return false if sdk_module?(owner)

      ancestors = self.class.ancestors
      index = ancestors.index(owner)
      index.nil? || index < ancestors.index(Type)
    rescue NameError
      false
    end

    def sdk_module?(mod)
      name = mod.name
      !name.nil? && (name == 'ClaudeAgentSDK' || name.start_with?('ClaudeAgentSDK::'))
    end

    # A key that is not an attribute, on a strict type: a typo the user
    # would otherwise never see.
    def unknown_attribute(name)
      klass = self.class
      raise ArgumentError, "#{klass.name || klass.inspect}: unknown attribute #{name.inspect} " \
                           "(known: #{klass.attribute_names.join(', ')})"
    end
  end
end
